let variable=[{
    name : "Jose Vicente",
    surname : "Jimenez Chamizo",
    age : "27",
    city : "Málaga",
    hobby : "Videojuegos",
    favoriteFood : "Pastel de carne",
    favoriteVideoGame : "League of Legends",
    favoriteFilm : "El Señor de los Anillos",
    favoriteBook : "Berserk",
    petName : "Kino",
},{
    name: "Ana",
    surname: "Montes",
    age: 22,
    city: "Arteixo",
    hobby: "jugar",
    favoriteFood: "lasaña",
    favoriteVideoGame: "Palia",
    favoriteFilm: "Señor de los Anillos",
    favoriteBook: "Epic",
    petName: "Kenma",
},{    
    name: "Karim",
    surname: "Felus",
    age: 26,
    city: "Barcelona",
    hobby: "jugar",
    favoriteFood: "Paella",
    favoriteVideoGame: "Fifa",
    favoriteFilm: "Tenet",
    favoriteBook: "Harry Potter Saga",
    petName: "Misha",
},{
    name: "Javier",
    surname:"Ruiz",
    age: 30,
    city: "Malaga",
    hobby: "Programar",
    favoriteFood: "Croquetas",
    favoriteVideoGame: "F1",
    favoriteFilm: "Cualquiera de Batman",
    favoriteBook: "Comic de Eterno Hallowen de Batman",
    petName: "No tengo",
},{
    name: "Javi",
    surname:"Hueso",
    age: 23,
    city: "Valencia",
    hobby: "Cine",
    favoriteFood: "Paella",
    favoriteVideoGame: "CoD",
    favoriteFilm: "Harry Potter",
    favoriteBook: "Lord of the Rings",
    petName: "Pepe",
}]

